### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by Natemo2625** [mt8163/android_device_amazon_karnak#1]
Does everything in this rom work properly as of now, or is there still work that needs to be done? Was going to try this on my karnak but didn't see much info here about it.

Edit: I answered my own question as I could not enter TWRP again and could not stop the reboot to TWRP loop, will come back later

**Comment by ivan-882** [comment]
If you are still locked out of twrp, you can use adb shell to delete the /data directory and that will let you use twrp to install whatever other rom you want to use.

**Comment by Natemo2625** [comment]
> If you are still locked out of twrp, you can use adb shell to delete the /data directory and that will let you use twrp to install whatever other rom you want to use.

Oh I didn't know I could do that, I just did the full unlock process again lol
