### ISSUE TITLE
WI-FI being disconnected while sleeping in pie

### ISSUE THREAD

**Issue by 488315** [mt8163/android_device_amazon_karnak#11]
while the device is sleeping for after 5 minutes or further
in the logcat it shows this. since we have enough ram in pie it still shows this. this issue has been persisting since nougat. i will need to find a fix for this 
09-30 14:13:19.178 14922 15007 E WifiVendorHal: stopRssiMonitoring(l.2404) failed {.code = ERROR_NOT_AVAILABLE, .description = }
09-30 14:13:19.196 15338 15338 E wpa_supplicant: wpa_driver_nl80211_driver_cmd: failed to issue private commands, error msg: Out of memory
09-30 14:13:19.196 14922 15007 E SupplicantStaIfaceHal: ISupplicantStaIface.setSuspendModeEnabled failed: {.code = FAILURE_UNKNOWN, .debugMessage = }
09-30 14:29:44.678 14922 15007 E WifiScanner: listener cannot be found
09-30 14:29:45.830   264   264 I wmt_launcher: fw log ctrl flag has been set
09-30 14:29:45.830   264   264 I wmt_launcher: fw dynamic ctrl flag has been set
09-30 14:29:47.832   264   264 I wmt_launcher: fw log ctrl flag has been set
09-30 14:29:47.832   264   264 I wmt_launcher: fw dynamic ctrl flag has been set
09-30 14:29:49.680 14922 15007 E WifiScanner: listener cannot be found

**Comment by 488315** [comment]
Fixed in pie with commit https://github.com/mt8163/android_device_amazon_karnak/commit/8051344c39a41f05625d8d558040661766790803#diff-daedfaa21d42dc78ea018a79db1b833f

Nougat still has that issue

**Comment by ShayBox** [comment]
You really don't have to create issues on your own project, it just spams anyone that would consider contributing.

**Comment by 488315** [comment]
@ShayBox Generally I use issues as a checklist as a road map. Like ggow did in his repository

**Comment by davwheat** [comment]
I disagree @ShayBox.

Yes, alternatives could be used, but this way there's record of fixed issues and by properly tagging commits (like "fixes #xx") you can easily identify which commit fixed an issue for future reference.
