### ISSUE TITLE
[Bug report] Camera2 API is "legacy" not "limited".

### ISSUE THREAD

**Issue by julianfairfax** [mt8163/android_device_amazon_karnak#23]
Hi,
I'm using the latest version of your LineageOS 16 ROM on my Fire Tablet. I want to use an app that requires the camera to scan a code. Unfortunately this app wasn't working. I tried it on a Fire Tablet with FireOS 7 where it worked just fine. I used an app to check the Camera2 API features and found that it's only supported in "legacy" mode on your ROM whereas as it's supported in "limited" mode on FireOS. Is there a way you or I could fix this and get "limited" Camera2 API support on my device in order to use this app? Thanks for your help and thanks so much for your work on this ROM.

**Comment by 488315** [comment]
ill implement the fix in 18.1

**Comment by julianfairfax** [comment]
Could that fix be added somehow to the LineageOS 16 build through a TWRP zip or something (I don't need a new build I just need to get this working). I don't want to upgrade to 18.1 if it doesn't have encryption and I'm fine with the current build. Thanks for your quick response btw! I wasn't expecting that.

**Comment by julianfairfax** [comment]
It looks like you fixed it in this commit which would mean I'd have to compile a new build of LineageOS 16 with these changes if I wanted to get that fix, right? That doesn't sound fun if so. https://github.com/mt8163/android_device_amazon_karnak/commit/89a78a7f295d2338fcf65edab9f0f879038a32d5

**Comment by julianfairfax** [comment]
Closing since this will be fixed, and I can't build LineageOS 16

**Comment by julianfairfax** [comment]
Sorry for closing and opening this again, I'll keep it open until I can test that implementation. Thanks for your wonderful ROM!

**Comment by julianfairfax** [comment]
I haven't yet checked the Camera2 API features, but the app I need to use doesn't work in the new 18.1 version. Also microG doesn't seem to be supported anymore?

**Comment by julianfairfax** [comment]
Can't test this anymore and won't benefit from the fix

**Comment by 488315** [comment]
Whats wrong now?

**Comment by julianfairfax** [comment]
I can't test new builds but the last build still had this issue

**Comment by julianfairfax** [comment]
Closing since I no longer have the device and can't test
