### ISSUE TITLE
Lack of README

### ISSUE THREAD

**Issue by DrRayThe2nd** [mt8163/android_device_amazon_karnak#8]
I would love to be able to build and test this as it is developed so that I may provide feedback, however, because there are no build instructions, I am unable to do so.

**Comment by R0rt1z2** [comment]
Seriously?
There's no need of any instructions. It's like a normal build:
source ./build/envsetup.sh
brunch lineage_karnak-userdebug

**Comment by DrRayThe2nd** [comment]
> Seriously?
> There's no need of any instructions. It's like a normal build:
> source ./build/envsetup.sh
> brunch lineage_karnak-userdebug

This is probably a stupid question, but there is no build folder in this repository. Do I need to clone the LineageOS source and move these files into that?

**Comment by R0rt1z2** [comment]
lmao.
Of course, you need to download LineageOS 14.1 Code and then clone vendor/kernel/device in their correct places.

**Comment by DrRayThe2nd** [comment]
Oh I see. Thank you for bearing with me.
